### ISSUE TITLE
argument -jvm4testexecution does not work

### ISSUE THREAD

**Issue by zhangjie-marina** [SpoonLabs/astor#111]
Hi there,

I am trying to run jGenprog on the projects from Defects4j. For some projects that are OK with Java8 (such as Math73b), if I don't use argument -jvm4testexecution, several patches will be generated, but if I add that argument, jGenprog fails to give a patch (the patch set is empty). For projects only OK with Java7, the argument does not work as well.

Cheers,

Jie

**Comment by martinezmatias** [comment]
Hi Jie
Could you send me the command lines that you have used and the corresponding ouputs (logs)?
Thanks
Matias
