### ISSUE TITLE
Creating astor.jar

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#145]
Trying to create astor.jar based on the instructions in the below document (Appendix)

https://hal.archives-ouvertes.fr/hal-01321615/document 

I downloaded astor
cd astor>
astor>mvn BUILD fails
astor>mvn package is again sort of infinite runs(doesn't create any jar as well)

Any inputs

**Comment by hsellik** [comment]
@ssk1216 , did you try `mvn package -DskipTests=true`?

This should skip tests and finish in a reasonable amount of time.
