### ISSUE TITLE
Improve Getting Started Documentation

### ISSUE THREAD

**Issue by hsellik** [SpoonLabs/astor#146]
During TU Delft course Software Testing and Reverse Engineering (CS4110), some students encountered issues while following the [Getting Started Guide](https://github.com/SpoonLabs/astor/blob/master/docs/getting-starting.md).
 
### Problem 1
After running the following line in terminal:

`mvn dependency:build-classpath | egrep -v "(^\[INFO\]|^\[WARNING\])" | tee /tmp/astor-classpath.txt`

The error thrown was:
```
Error: Could not find or load main class Scanning
Caused by: Java.lang.ClassNotFoundException: Scanning
```

There are 2 problems with this:  
1) Lines in maven logs for Downloading of dependencies do not start with [INFO] or [WARNING]. Therefore egrep regex doesn't remove them.  
2) Some kind of encoding/tee command/ubuntu 18.04 issue which makes `astor-classpath.txt` lines look like
`[ESC[1;34mINFOESC[m] Scanning for projects...`
Again, this makes the egrep regex unable to delete these lines.

Solution:
Remove lines starting with `Downloading...` and `[INFO]` / `[WARNING]` by hand from `/tmp/astor-classpath.txt` or worse, change the command to `mvn dependency:build-classpath | egrep -v "(INFO|WARNING)" | tee /tmp/astor-classpath.txt`. Latter presumes no Downloading by maven and no paths named INFO or WARNING in classpath (unlikely, but still possible).

### Problem 2
This is more basic, but still worth mentioning. After overcoming the classpath issue, users might get:
1) `Exception in thread "main" java.lang.IllegalArgumentException: The bin folder /home/user/astor/examples/Math-issue-280/target/classes does not exist`

Solution, run `mvn compile` in `astor/examples/Math-issue-280/`.  
  
2) `Exception in thread "main" java.lang.IllegalArgumentException: The bin folder /home/user/astor/examples/Math-issue-280/target/test-classes does not exist`

Solution: run `mvn test-compile` in `astor/examples/Math-issue-280/`.

### Problem 3
Building the jar. There is no documentation for this and it takes forever if running `mvn package` instead of `mvn package -DskipTests=true`.  Also described in #145 .

**Comment by monperrus** [comment]
Hi Hendrig,

Awesome that Astor is used at TU Delft :-)

Would you create three pull-requests to fix those three relevant problems?

That would be really cool, thanks!

**Comment by hsellik** [comment]
@monperrus Yeah, I can. 

Problem 2 should be solved by following steps, but people fail to `mvn clean compile # compiling  astor`. I shall create a FAQ for it?

**Comment by monperrus** [comment]
excellent, thanks a lot. yes, let's do add a FAQ as subsection in the getting-started.md file

**Comment by hsellik** [comment]
Apparently problem 1 is caused by maven [coloring the ouptut](https://askubuntu.com/questions/983410/when-i-redirect-maven-commands-the-file-looks-wrongly-encoded). 

I'll make a pull request to fix it.

**Comment by hsellik** [comment]
@monperrus 

Once PR-s #148 and #149 get merged all problems in this issue are solved.

**Comment by martinezmatias** [comment]
Thanks a lot @hsellik
