### ISSUE TITLE
Build Failure: there are test failures while mvn install

### ISSUE THREAD

**Issue by wsyzzz** [SpoonLabs/astor#161]
Hi, thx for your repository firstly.
When using Option 1 to get the start, I used `sudo mvn install` and got ERROR like below. My environment is Ubuntu18.04x64 and Java8.
Could you give me any pieces of advice about this? Thx.

Tests run: 367, Failures: 22, Errors: 234, Skipped: 60
[INFO] ------------------------------------------------------------------------
[INFO] **BUILD FAILURE**
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:12 h
[INFO] Finished at: 
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal **org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test)** on project astor: **There are test failures**.
[ERROR] 
[ERROR] Please refer to **/home/astor/target/surefire-reports** for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by olli22221** [comment]
I have the same problem.
Could anyone help?

**Comment by martinezmatias** [comment]
Hello @olli22221 @wsyzzz 

There were a mistake in the documentation (I've just updated): when installing we should not run the test case (the most important test cases are executed on travis, and we check they always pass). However, in the code base we have some test cases that fails that we must delete.
