### ISSUE TITLE
Execution Astor

### ISSUE THREAD

**Issue by Somdutta** [SpoonLabs/astor#162]
Hi,

I have built Astor using option 1. I am trying to execute it using the example given i.e. math_70. When I run the command it says "Error: Could not find or load main class fr.inria.main.evolution.AstorMain". I am in the astor directory. 

My entire command is:
java -cp astor.jar fr.inria.main.evolution.AstorMain -mode jkali -location /Users/somdutta/astor/examples/math_70 -mode statement -package org.apache.commons -failing org.apache.commons.math.analysis.solvers.BisectionSolverTest -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes -bintestfolder /target/test-classes -flthreshold 0.5 -stopfirst true -dependencies /Users/somdutta/astor/examples/libs/junit-4.4.jar,/Users/somdutta/astor/examples/libs/hamcrest-core-1.3.jar

Could you please advise.

Thanks
Somdutta

**Comment by crimsonfan** [comment]
Have you fixed it?
I have the same problem

**Comment by Somdutta** [comment]
Unfortunately, I have not found a solution to the problem I was having.

**Comment by VinayKabadi** [comment]
I am also stuck with the same problem... if anyone has found a solution would appreciate your response to this problem

**Comment by VinayKabadi** [comment]
Copy target/astor-1.0.0-SNAPSHOT-jar-with-dependencies.jar outside the target folder as rename as astor.jar
