### ISSUE TITLE
What's the fault localization tool used by Astor

### ISSUE THREAD

**Issue by Kaka727** [SpoonLabs/astor#171]
Hi, dear authors.
I note that there are two tools in the FL folder of Astor files (CocoSpoon and GZoltar).
From my execution log, I find it is currently based on GZoltar.
So does it mean that currently, all the five APR tools under this framework locate faulty code using GZoltar?

**Comment by martinezmatias** [comment]
Hi @Kaka727 
Yes, by default, all the approaches use GZoltar.
Cheers
Matias

**Comment by Kaka727** [comment]
@martinezmatias 
Hi, dear author, I find in the /lib/ package there are many versions of GZoltar like 0.1, 1.5 and 1.6. So what's exactly is the version used by Astor.
Thanks~

**Comment by martinezmatias** [comment]
Hi @Kaka727 
The version currently used by GZoltar is specified here:
https://github.com/SpoonLabs/astor/blob/master/pom.xml#L75
Regards
Matias

**Comment by Kaka727** [comment]
Thanks~ 
Very important information.

**Comment by tdurieux** [comment]
You should maybe fix the automatic deploy,  it was done on `fr.inria.astor.test.repair.approaches.IntroClassTest` but this test has been commented in .travis.yml. You should decide to use a different one.
