### ISSUE TITLE
GitLab Integration of Astor

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#193]
How to integrate Astor to GitLab??  Is there any support document about this?

**Comment by martinezmatias** [comment]
Hi @ssk1216 
I did not well understand this issue. 
What do you want to do?
Thanks
Matias

**Comment by ssk1216** [comment]
When I commit a  java source code on gitlab , I would like the Astor to be invoked and patches listed.

**Comment by martinezmatias** [comment]
Hi @ssk1216 
Astor does not include that functionality.
You would need to create your tool (e.g., a bot) that triggers Astor each time a commit is done in the platform.

**Comment by ssk1216** [comment]
Thanks

**Comment by martinezmatias** [comment]
FYI: we have created a software Bot called Repairnator that does something similar at want you need. Please check here the article https://hal.inria.fr/hal-02267512/document 
and the code is here: https://github.com/eclipse/repairnator

**Comment by ssk1216** [comment]
Yes, I am aware of Repairnator. Brilliant idea. 
My thoughts are how could I come up partial repairs and then based on subsequent inputs/code change from user re-run the test and suggest new repair ideas until a final fix is created.

**Comment by martinezmatias** [comment]
Hi @ssk1216 
It a great idea and a strong challenge.
Let's discuss it in other Issue.
Cheers
Matias
