### ISSUE TITLE
Upgrade Gzoltar to 1.7.2

### ISSUE THREAD

**Issue by martinezmatias** [SpoonLabs/astor#197]
One option could be to keep both GZoltar as different implementations of the same extension point (FautlLocalization)

**Comment by martinezmatias** [comment]
@tdurieux  
Have you tried version Gzoltar 1.7.2?  Do you know if it's able to run Junit5 test cases? (The old version we currently use (0.1.1) fails on Astor)

**Comment by tdurieux** [comment]
I did not try 1.7.2, I did not even know that this version existed.

**Comment by martinezmatias** [comment]
Gzoltar 0.1.1. seems buggy with JDK 11 on linux

**Comment by martinezmatias** [comment]
We continue with version 0.1.1 which is more stable than 1.7.2.
