### ISSUE TITLE
EXASTOR and SCAFFOLD modes

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/astor#199]
EXASTOR and SCAFFOLD are two modes of repair in the Astor list, which I cannot find documentation for them. What are these modes? Are they new repair tools which has just added to the Astor?

Also, I was trying to use 3sfix, but I could not find its mode in the list. Is it available in Astor? 

Also, what is "-clonegranularity" argument in DeepRepair?  

Thank you in advance for your time and consideration.

**Comment by monperrus** [comment]
> EXASTOR and SCAFFOLD are two modes of repair in the Astor list ... Are they new repair tools which has just added to the Astor? 

Yes, they are ongoing research projects.

> Also, I was trying to use 3sfix, but I could not find its mode in the list. Is it available in Astor?

Yes, it should be in the list. The corresponding publication is http://arxiv.org/pdf/1811.05703

Would you create a PR to add it in the list? Thanks!

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your respond. 
I get the following error when I want to use 3sfix mode. 
 
Unknown mode of execution: '3sfix',  modes are: [DeepRepair, CARDUMEN, jGenProg, jKali, MutRepair, EXASTOR, SCAFFOLD, custom]

I am doing PhD in UCF and I am going to create a PR tool for Java. But at the moment I am interested to work with PR tools for Java.

Also, I have a question about DeepRepair. What is "-clonegranularity" argument in DeepRepair?

**Comment by monperrus** [comment]
Hi Amirfarhad,

Thanks for you interest in Astor.

Could you create one issue per topic, one bug report for 3sfix and one question for DeepRepair?

Thanks! --Martin

**Comment by monperrus** [comment]
Closing this question about EXASTOR and SCAFFOLD
