### ISSUE TITLE
Constants of an expression template are replaced by Cardumen(?)

### ISSUE THREAD

**Issue by khaes-kth** [SpoonLabs/astor#200]
Hello,

As far as I understand, [Cardumen paper](https://arxiv.org/abs/1712.03854) says that only variables could be replaced in an expression template. However, it seems that in some of the patches constants are replaced as well.

In [this patch](https://github.com/SpoonLabs/astor-experiments/tree/master/cardumen-patches/unformatted-patches/Math/Math28#patch-diff-3), [this expression](https://github.com/khaes-kth/coming/blob/52e7c474b00618c4799058aa6b724b1c27965c30/src/main/resources/repairability_test_files/cardumen/cardumen1/cardumen/one/cardumen_one_s.java#L104) is replaced by [this expression](https://github.com/khaes-kth/coming/blob/52e7c474b00618c4799058aa6b724b1c27965c30/src/main/resources/repairability_test_files/cardumen/cardumen1/cardumen/one/cardumen_one_t.java#L104). However, in the [original version of the file](https://github.com/khaes-kth/coming/blob/52e7c474b00618c4799058aa6b724b1c27965c30/src/main/resources/repairability_test_files/cardumen/cardumen1/cardumen/one/cardumen_one_s.java) there is no expression that can be seen as the template of `Precision.equals(entry, 0.0, maxUlps)` unless constants, such as 1.0, (and not only variables) could be replaced as well, in which case the expression in [this line](https://github.com/khaes-kth/coming/blob/52e7c474b00618c4799058aa6b724b1c27965c30/src/main/resources/repairability_test_files/cardumen/cardumen1/cardumen/one/cardumen_one_s.java#L123) can be seen as the desired template.

Should Cardumen be implemented in a way that constants could be changed in an expression template as well as variables?

Thanks @martinezmatias @monperrus

**Comment by monperrus** [comment]
Yes, the constants are considered in Cardumen, they could be changed according to the scope. See Cardument code.
