### ISSUE TITLE
3sfix is not in the mode list

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/astor#201]
I get the below error when I want to use 3sfix mode. How can I use 3sfix?

Unknown mode of execution: '3sfix', modes are: [DeepRepair, CARDUMEN, jGenProg, jKali, MutRepair, EXASTOR, SCAFFOLD, custom]

**Comment by monperrus** [comment]
you have to call [fr.inria.astor.approaches._3sfix.Main](https://github.com/SpoonLabs/astor/blob/master/src-3sfix/main/java/fr/inria/astor/approaches/_3sfix/_3sFix.java)

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your help. 

I can see the directory of "src-3sfix" after installing Astor, which has "_3sfix.java" and other java codes. However, when I want to use it with the command line that I used for other 4 tools I get an Error message. The message says that "3sfix" is not among the supported modes, you can find the message in my first comment.

Should I use it in a different way? Or, Is any problem with 3sfix at the moment?

**Comment by monperrus** [comment]
Yes, 3sfix is **not** to be used with the command line you used.

A pull-request to add support for the main command line would be much appreciated :)

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you so much.

**Comment by monperrus** [comment]
You're welcome, happy to help :)
