### ISSUE TITLE
Confusion regarding GZoltar Version used by jGenProg, jMutRepair, DeepRepair, Cardumen 

### ISSUE THREAD

**Issue by mou23** [SpoonLabs/astor#219]
From the paper "Astor: Exploring the Design Space of Generate-and-Validate Program Repair beyond GenProg", it is clear that jGenProg, jMutRepair, DeepRepair, Cardumen use GZoltar for fault localization. But how can I know which version do they use?

Thanks in advance.

**Comment by martinezmatias** [comment]
Hi @mou23 

Do you mean which version of GZoltar do Astor uses? 
Its gzoltar 0.1.1

**Comment by mou23** [comment]
Oh. Thank you so much
