### ISSUE TITLE
Could not find or load main class fr.inria.main.evolution.AstorMain

### ISSUE THREAD

**Issue by crimsonfan** [SpoonLabs/astor#222]
I followed the option 1 trying using jkali mode but got the message "Could not find or load main class fr.inria.main.evolution.AstorMain".
My command is "java  -cp astor.jar fr.inria.main.evolution.AstorMain -mode jkali -location /d/Project/NewFolder2/astor/target/classes/fr/inria/main/evolution".
Need help.
Thanks.

**Comment by martinezmatias** [comment]
Hi @crimsonfan  
Are you executing the command in the same folder that the file 'astor.jar' is located?

I have just try the command and I works. I can reproduce the error when I execute the command  from other folder that the one having the jar. So, candidate solutions: execution the command on the same folder or use an absolute path.

**Comment by crimsonfan** [comment]
Thanks a lot, I solved it
