### ISSUE TITLE
Command line argument -failing

### ISSUE THREAD

**Issue by jose** [SpoonLabs/astor#225]
Hi,

Does the `-failing` argument support test suites, test cases, or both?

At the very beginning of section [Command line arguments](https://github.com/SpoonLabs/astor/blob/master/docs/getting-starting.md#command-line-arguments) `-failing` argument is defined as 'test case':
```
-failing "failing test case" (if there are several failing test case, give them separated by the classpath separator (: in linux/mac  and ; in windows)
```
However, in section [Command line arguments example Math-70 from Defects4J](https://github.com/SpoonLabs/astor/blob/master/docs/getting-starting.md#command-line-arguments-example-math-70-from-defects4j) the same argument is defined as 'test class'
```
-failing org.apache.commons.math.analysis.solvers.BisectionSolverTest
```

Could you please clarify?

--
Best,
Jose

**Comment by martinezmatias** [comment]
Hi @jose 
> Could you please clarify?

Thanks for remark, I updated the documentation. (commit da8a267)

> Does the -failing argument support test suites, test cases, or both?

It supports test cases: the parameter allows to specify only the test cases that fail. Astor will automatically search for the other (passing) test cases used for validating regression.

Thanks!
Regards
Matias

**Comment by jose** [comment]
Thanks @martinezmatias, but it isn't clear yet.

You just said _"It supports test cases: the parameter allows to specify only the test cases that fail."_ but your commit says _"canonical names of classes with failing test cases"_.  The former implies test methods and the latter implies test classes.  I believe the latter is the correct definition right?


--
Best,
Jose

**Comment by martinezmatias** [comment]
Hi @jose 
Sorry, my comment added more confusion. 
The latter explanation you mention (that one from the commit is the correct).

> It supports test cases: the parameter allows to specify only the test cases that fail. Astor will automatically search for the other (passing) test cases used for validating regression.

I wanted to say that the parameter supports the name of class with test cases, and it does not support names of classes  that correspond to Test Suites.

Regards
Matias
