### ISSUE TITLE
Running with own programs - No suspicous gen for analysis

### ISSUE THREAD

**Issue by 11CConnolly** [SpoonLabs/astor#228]
Hi, I'm trying to run Astor with my own small programs and test suites, however when I run I get an error

> Exception in thread "main" java.lang.IllegalArgumentException: No suspicious gen for analyze. 

My program has been run with "sudo mvn clean compile" etc. and the command I'm running is below

> java -cp astor.jar fr.inria.main.evolution.AstorMain -location /home/cal/SECdefects/ -mode jgenprog -package org.apache.commons -failing cc14g17.CWE20_Improper_Input_Validation -srcjavafolder /src/java -srctestfolder /src/test -stopfirst true -dependencies /home/cal/SECdefects/target

(astor.jar is properly referenced)

The minimum suspicion is set at 0.1 and the failing test is correctly identified as being failing.

**Comment by 11CConnolly** [comment]
An issue of setting package as org.apache.commons - which has now been set to the package of the project. Issue has been solved and solutions are generated.

**Comment by martinezmatias** [comment]
Hi @11CConnolly 
Great! Nice to hear that it works :)
Regards
Matias
