### ISSUE TITLE
NullPointerException when running AstorMain.execute(args)

### ISSUE THREAD

**Issue by javierron** [SpoonLabs/astor#238]
I have traced the issue and it seems that the `location` configuration property is being required here:
 https://github.com/SpoonLabs/astor/blob/352355e4e9f335427a75cd78303e3d37064802c6/src/main/java/fr/inria/main/AbstractMain.java#L378

https://github.com/SpoonLabs/astor/blob/352355e4e9f335427a75cd78303e3d37064802c6/src/main/java/fr/inria/astor/core/setup/ProjectConfiguration.java#L274

Before being stored in the properties map here:

https://github.com/SpoonLabs/astor/blob/352355e4e9f335427a75cd78303e3d37064802c6/src/main/java/fr/inria/main/AbstractMain.java#L396

It might be related to: https://github.com/SpoonLabs/astor/issues/236

**Comment by martinezmatias** [comment]
Hi @javierron 
Do you have the command you use to launch Astor?
Thanks
Matias

**Comment by javierron** [comment]
Sure, you can see the call here:

https://github.com/eclipse/repairnator/blob/4fc54a2194a6def3785ea1a51a3bfb9efb2e68fc/src/repairnator-pipeline/src/main/java/fr/inria/spirals/repairnator/process/step/repair/sequencer/detection/AstorDetectionStrategy.java#L52

This worked on version `20190919`, but breaks in version `1.0.0-SNAPSHOT` after I upgraded to get the fix for the GZoltar exception.

**Comment by martinezmatias** [comment]
Hi Javier
Do you have the stack trace of the NPE?
Thanks!
Regards
Matias
