### ISSUE TITLE
Check variant before validation

### ISSUE THREAD

**Issue by crimsonfan** [SpoonLabs/astor#239]
Dear @martinezmatias ,

It's me again.
I wonder to ask that if I can check the code of variant (read the source code) before astor validates it by test suite?
If yes, where can I find the hardcode location?

Thanks,
Tin.

**Comment by martinezmatias** [comment]
Dear @crimsonfan 

> It's me again

Nice to know that you continue using Astor :)

 > I can check the code of variant (read the source code) before astor validates it by test suite?

Yes. There are some ways. The easiest one would be to use the parameters `saveall:true` via the argument `-parameters ` .
This produces that Astor stores the files under modification *before* validating it.  
Thus, in the output you can find "program-variant-x" (x is the Identifier).

Could that work for you?

**Comment by crimsonfan** [comment]
Dear @martinezmatias,

Sure, I have firgured out right after I posted the question, sorry for my troublesomes.
Just an outline question, do you think in a large and ideal project (classes are named professionally), two classes with the same name can be existed?
I'm going to use file.io to find the bugged class and the fixed class by the fixed class name for comparison, and I affraid that maybe there are two classes with the same name, and the comparison maybe nonsense.

Thanks,
Tin.

**Comment by martinezmatias** [comment]
Hi @crimsonfan 

> Just an outline question, do you think in a large and ideal project (classes are named professionally), two classes with the same name can be existed?

It could happen. I have seen some real project that have two classes with the same name and are located in different packages or modules.

**Comment by crimsonfan** [comment]
Dear @martinezmatias ,
Last but not least, in the output_astor, the folder default is the folder of the project under repair?

Thanks,
Tin.

**Comment by martinezmatias** [comment]
Hi @martinezmatias 
>  the folder default is the folder of the project under repair?
Yes, exactly, it has the original buggy project.

 > Last but not least

There is no problem. Write me if you need some help :)

**Comment by crimsonfan** [comment]
Hi @martinezmatias ,

Thanks for all.

Hope you have a nice day,
Tin.
