### ISSUE TITLE
Codeformated vs !codeformated

### ISSUE THREAD

**Issue by crimsonfan** [SpoonLabs/astor#240]
Dear @martinezmatias ,

Inside the folder of astor_output's project, for each variant, I found variant-n folder and variant-n-f one.
I wonder what is the differencies of these.

Thanks,
Tin.

**Comment by martinezmatias** [comment]
Hi @crimsonfan 

One produces that the modified files  preserves the line numbers of the original files. The other produces that the modified files are completely formatted (e.g., remove white lines).

Regards
Matias

**Comment by crimsonfan** [comment]
Dear @martinezmatias ,

Thanks for your reply.
