### ISSUE TITLE
[Feature] Add anti-pattern to improve jGenProg2

### ISSUE THREAD

**Issue by WuYff** [SpoonLabs/astor#245]
As the paper [Automatic Repair of Real Bugs in Java: A Large-Scale Experiment on the Defects4J Dataset](https://hal.archives-ouvertes.fr/hal-01387556/document) illustrated,  jGenProg2 can generate patches that are only test-suite adequate (they pass the test suite but are incorrect beyond the test-suite satisfaction correctness criterion). Let's call these patches ***plausible patches*** here.

One solution to alleviate this problem is proposed in the paper [Anti-patterns in Search-Based Program Repair](https://www.shinhwei.com/anti-patterns-camera-ready.pdf).  ***Anti-pattern*** is a set of forbidden transformations, such as simply deleting control statements ( if and loops ) or adding early exit. We can apply anti-patterns in automated repair tools to capture disallowed modifications to the buggy program and eventually prevent generating some plausible patches.

We've experimented on jGenProg2 with anti-pattern implemented. We successfully generated patches for 14 Defects4J  bugs with the original jGenProg2 (1 correct patch and 67 plausible patches). After anti-pattern is implemented, the number of generated plausible patches  is reduced from 67 to 29 for these 14 bugs in total, and the average repair time is reduced by 22.6% (as shown in the table below). Thus, we have proved the effectiveness of anti-patterns to improve jGenProg2. 

Nevertheless, anti-patterns can potentially affect the generation of correct patches, e.g. if the correct patch requires simple deletion of if-statements or loops. To conquer this defect, we can integrate anti-patterns as an option (a command-line parameter). Users can choose whether to use it or not.

To support open science, we would like to open a pull request for sharing our implementation.

Could you help to review our pull request?

<img width="577" alt="evaluation_result" src="https://user-images.githubusercontent.com/39701893/93253443-72849480-f7c9-11ea-8b6f-9e44c67e338e.png">

**Comment by martinezmatias** [comment]
Dear @WuYff 
Thanks a lot for sharing the Java implementation of Anti-patterns with us and with the community.
We appreciate that.
For curiosity, are the results from your experiment (e.g. Table you put in this issue) published somewhere? 
Thanks
Matias

**Comment by WuYff** [comment]
Dear @martinezmatias 
Yes, it is going to appear in [ASE SRC 2020](https://conf.researchr.org/track/ase-2020/ase-2020-student-research-competition#event-overview), a short paper titled "Anti-patterns for Java Automated Program Repair Tools".
Thanks,
Yi Wu

**Comment by martinezmatias** [comment]
Hi @WuYff 
> Yes, it is going to appear in ASE SRC 2020, a short paper titled "Anti-patterns for Java Automated Program Repair Tools".

Great, congratulations!

**Comment by martinezmatias** [comment]
Dear @WuYff 
Thanks a lot for the contribution. It's perfect. 
I have just merged.
I added your name in the list of Astor contributors :)
Regards
Matias
