### ISSUE TITLE
Error running astor on Math_70

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#292]
java  -cp astor.jar fr.inria.main.evolution.AstorMain -mode jMutRepair -location /home/linuxadmin/Desktop/astor/examples/math_70 -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes -bintestfolder /target/test-classes -dependencies home/linuxadmin/Desktop/astor/examples/libs/junit-4.4.jar

Executing the above command, results in the below error?? 

ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern

**Comment by monperrus** [comment]
This is a problem in the log configuration file. Note that the logging 
infrastructure was updated in
https://github.com/SpoonLabs/astor/pull/290

**Comment by MaximoOliveira** [comment]
I cloned the latest version of Astor and am having the same problem:

By following option 1 and executing: 

`java -cp /home/max/Desktop/tese/astor/target/astor-1.0.0-SNAPSHOT-jar-with-dependencies.jar fr.inria.main.evolution.AstorMain -mode jMutRepair -location /home/max/Desktop/tese/astor/examples/math_70 -srcjavafolder /src/java/ -srctestfolder /src/test/ -binjavafolder /target/classes -bintestfolder /target/test-classes -dependencies /home/max/Desktop/tese/astor/examples/libs/junit-4.4.jar`

I get the same error:
![image](https://user-images.githubusercontent.com/36827697/104012711-93298d80-51b0-11eb-9377-1d75061efb26.png)

Any suggestions on steps to take to surpass this problem? 

Thank you!
