### ISSUE TITLE
Is Astor's output deterministic? 

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [SpoonLabs/astor#300]
Are Astor outputs for jKali, jGenProg, jMutRepair, and Cardumen deterministic? Or the output validated patch can be different by each run (by using the same machine and test suite for each run with the Astor framework's default setting).

**Comment by martinezmatias** [comment]
In theory it should be deterministic. It provides an argument 'seed' to control the randon seed.

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you for your help.
