### ISSUE TITLE
Unable to clone Astor

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#303]
git clone https://github.com/SpoonLabs/astor.git
Cloning into 'astor'...
fatal: unable to access 'https://github.com/SpoonLabs/astor.git/': Operation timed out after 300032 milliseconds with 0 out of 0 bytes received

Did any one face a similar issue ?

**Comment by martinezmatias** [comment]
Hi @ssk1216 

> Did any one face a similar issue ?

No, I haven't.

Could you clone it?

Regards
Matias

**Comment by byteSamurai** [comment]
As I cloned it several times today..
@ssk1216 possibly a local problem?
Can you clone any other project?
Are you behind a proxy?

**Comment by ssk1216** [comment]
Thanks & no issues now .
