### ISSUE TITLE
Why Lib in repo

### ISSUE THREAD

**Issue by Certseeds** [SpoonLabs/astor#311]
I found the repo size is bigger than 200mb, why do you place a big lib folder in repo?

**Comment by martinezmatias** [comment]
Hi @Certseeds 

> I found the repo size is bigger than 200mb, why do you place a big lib folder in repo?

Most of the libs that are included in that folder are libraries used by the buggy applications under testing.
Thus, they are not added in the classpath of Astor. (For this reason, those libs are not added in the maven pom).

Regards
Matias
