### ISSUE TITLE
integrate flacoco in Astor

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/astor#314]
for @andre15silva

**Comment by martinezmatias** [comment]
Initial implementation: [FlacocoFaultLocalization](https://github.com/SpoonLabs/astor/blob/76279a3fb9085d78e799c0b30fb14459e7bde9eb/src/main/java/fr/inria/astor/core/faultlocalization/flacoco/FlacocoFaultLocalization.java)

Some test cases (to refactor and fix) [FaultLocalizationExtensionTest](https://github.com/SpoonLabs/astor/blob/76279a3fb9085d78e799c0b30fb14459e7bde9eb/src/test/java/fr/inria/astor/test/repair/evaluation/extensionpoints/faultlocalization/FaultLocalizationExtensionTest.java)

**Comment by andre15silva** [comment]
Introducing `flacoco` as the first dependency of `astor` results in the following example classpath while running `test-runner`:

```
(...):/home/andre/.m2/repository/eu/stamp-project/test-runner/3.0.0-SNAPSHOT/test-runner-3.0.0-SNAPSHOT.jar:/home/andre/.m2/repository/org/jacoco/org.jacoco.core/0.8.1/org.jacoco.core-0.8.1.jar:/home/andre/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/andre/.m2/repository/org/pitest/pitest-entry/1.4.7/pitest-entry-1.4.7.jar
````

If it is introduced as the last dependency of `astor`, it results in this:
```
(...):/home/andre/.m2/repository/eu/stamp-project/test-runner/3.0.0-SNAPSHOT/test-runner-3.0.0-SNAPSHOT.jar:/home/andre/.m2/repository/org/jacoco/org.jacoco.core/0.8.1/org.jacoco.core-0.8.1.jar:/home/andre/.m2/repository/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/andre/.m2/repository/org/ow2/asm/asm/6.0/asm-6.0.jar
```

and `test-runner` fails.

This means there is some collision with other `astor` dependencies. It could also indicate that the classpath construction in either `flacoco` and/or `test-runner` could be improved to be more stable.

**Comment by andre15silva** [comment]
Update: small projects are working with no issue, but larger projects such as the `math` and `lang` ones are currently failing.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

Thanks for the update.

> larger projects such as the math and lang ones are currently failing, due to an error in test-runner.

Is that failure related to the length of the command line? Reported in [Issue 57 from TestRunner](https://mail.google.com/mail/u/0/#inbox/FMfcgzGkZQHdPFQRQRwXkgnSkdPbPljz)?

**Comment by andre15silva** [comment]
> Hi @andre15silva
>
> Thanks for the update.

Hi @martinezmatias 
 
> Is that failure related to the length of the command line? Reported in [Issue 57 from TestRunner](https://mail.google.com/mail/u/0/#inbox/FMfcgzGkZQHdPFQRQRwXkgnSkdPbPljz)?

No, it's a different issue which I haven't been able to pin point. It happens during the execution of test cases, but it doesn't always fail during the execution of the same test case. I'll open a PR today with the small and big projects so you can see.

**Comment by martinezmatias** [comment]
> I'll open a PR today with the small and big projects so you can see.

Perfect, thanks

**Comment by andre15silva** [comment]
FYI @martinezmatias ,

I think I have identified the issue with the large projects. See https://github.com/STAMP-project/test-runner/issues/108.

Hoping to have a PR to fix this in `test-runner` today and then test here.

**Comment by martinezmatias** [comment]
Thanks for the update @andre15silva .

**Comment by andre15silva** [comment]
With https://github.com/STAMP-project/test-runner/pull/110 and https://github.com/SpoonLabs/flacoco/pull/64, `flacoco` can handle large projects such as the `mathXX` ones.

Now the issue is understanding and possibly fix the discrepancies between gzoltar and flacoco results.

**Comment by martinezmatias** [comment]
Perfect @andre15silva !
