### ISSUE TITLE
Incorrect process of `java_home`

### ISSUE THREAD

**Issue by qiujiangkun** [SpoonLabs/astor#328]
Mmy `java_home` is somehow set to `/home/jack/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrx-8u202-linux-x64-b1483.24/extracted/jre` and I don't have control over it, but the `javalocationbin` is set to `/home/jack/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/jbrx-8u202-linux-x64-b1483.24/extracted/bin`, which is not the case. It should be `....../jre/bin`

```java
if (location.getName().equals("jre")) {
	javahome = location.getParent() + File.separator + "bin";
	File javalocationbin = new File(javahome);
	if (!javalocationbin.exists()) {
		System.err.println("Problems to generate java jdk path");
		return false;
	}
}
```

**Comment by qiujiangkun** [comment]
Update: I noticed that the jre structure is different.

**Comment by martinezmatias** [comment]
Hi @qiujiangkun 

> Update: I noticed that the jre structure is different.

Fine.

Regards
Matias

**Comment by martinezmatias** [comment]
Hi @qiujiangkun 

> Update: I noticed that the jre structure is different.

Fine.

Regards
Matias
