### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by andre15silva** [SpoonLabs/astor#333]
After https://github.com/SpoonLabs/astor/pull/323, we should release a new version (maybe a major?), so that we can use flacoco through astor in sequenceR (see https://github.com/eclipse/repairnator/issues/1239)

**Comment by martinezmatias** [comment]
Hi @andre15silva 

I agree. having a new default FL is a major change, as Astor would be able to manipulate more recent java programs

**Comment by monperrus** [comment]
great, thanks Matias.

**Comment by martinezmatias** [comment]
Hi @andre15silva 

new version of Astor (2.0.0) released.
See here: https://oss.sonatype.org/

**Comment by monperrus** [comment]
hurray!
