### ISSUE TITLE
Questions about TIBRA

### ISSUE THREAD

**Issue by jianghc2116** [SpoonLabs/astor#349]
Hello, I have successfully run the jgenprog repair tool, but I want to use the Tibra method. How should I run the program?
Second, I want to set the jgenprog method to expression granularity. What should I do? Directly use - mode expression or what I need to modify? thank you!

**Comment by martinezmatias** [comment]
Hi @jianghc2116 

> I want to use the Tibra method. How should I run the program?

You can activate it using the command line parameter:  `-customengine fr.inria.astor.approaches.jgenprog.extensionTibraApproach`

> Second, I want to set the jgenprog method to expression granularity.

By default, it works at the level of statements. It could be possible to work at the level of method, but you rewrite all operators in order they work at that granularity.

Regards
Matias

**Comment by jianghc2116** [comment]
> Hi @jianghc2116
> 
> > I want to use the Tibra method. How should I run the program?
> 
> You can activate it using the command line parameter: `-customengine fr.inria.astor.approaches.jgenprog.extensionTibraApproach`
> 
> > Second, I want to set the jgenprog method to expression granularity.
> 
> By default, it works at the level of statements. It could be possible to work at the level of method, but you rewrite all operators in order they work at that granularity.
> 
> Regards Matias

for question 2, am I going to rewrite all the methods here? /fr/inria/astor/approaches/jgenprog/operators
