### ISSUE TITLE
Can not produce source code repairs

### ISSUE THREAD

**Issue by ruizhengu** [SpoonLabs/astor#365]
Astor can produce class file repairs but can not produce source code level repairs.
![image](https://github.com/SpoonLabs/astor/assets/115544679/e9122ab7-5736-4b6f-a7b2-e3fd0be5b292)
![image](https://github.com/SpoonLabs/astor/assets/115544679/67ea9c64-3728-41bc-a492-0aa9b95f5bb4)

**Comment by martinezmatias** [comment]
Hello, 
Could you show me the printed output?

**Comment by ruizhengu** [comment]
I found that if there is no patch generated (i.e. the list `patches` is empty in _/output_astor/AstorMain-xxx/astor_output.json_), there will be no source code generated in _/output_astor/AstorMain-xxx/src/variant-x_ (but it will still be class files in _/output_astor/AstorMain-xxx/bin/variant-x_).
