### ISSUE TITLE
Path too long

### ISSUE THREAD

**Issue by martingwhite** [SpoonLabs/astor#42]
Is it possible to rename the directory `astor/examples/introclass/3b2376...` using a shorter name? Otherwise paths in that subtree are too long for some systems when extracting or cloning.

**Comment by martinezmatias** [comment]
Hi Martin
> Is it possible to rename the directory astor/examples/introclass/3b2376... using a shorter name? 
Sure. Commit 9061fb6bc95c4e004c205d0d85e3742f7d3b7c64 introduces those changes.
Best
Matias
