### ISSUE TITLE
Undefined cases

### ISSUE THREAD

**Issue by martingwhite** [SpoonLabs/astor#44]
Running example `bug288` produces the following errors:

> [ERROR] fr.inria.astor.core.manipulation.sourcecode.VariableResolver.fitInPlace(VariableResolver.java:308) -
> Undefined case spoon.support.reflect.code.CtThisAccessImpl
> [ERROR] fr.inria.astor.core.manipulation.sourcecode.VariableResolver.fitInPlace(VariableResolver.java:308) -
> Undefined case spoon.support.reflect.code.CtNewArrayImpl
> [ERROR] fr.inria.astor.core.manipulation.sourcecode.VariableResolver.fitInPlace(VariableResolver.java:308) -
> Undefined case spoon.support.reflect.code.CtConditionalImpl

My environment references `spoon-core-5.1.0.jar`.

**Comment by martinezmatias** [comment]
Hi Martin
Thanks for pointing me the issue.
Currently, I'm working on VariableResolver to manage those cases. I plan to introduce some improvement in that class.
Best
Matias

**Comment by martinezmatias** [comment]
Hi Martin, 
I finished this issue. Changes are introduced at commit 100624d1f9149f88548a190f97eb44986032f111
