### ISSUE TITLE
Missing dependence "org.eclipse.jdt.core:3.12.0.v20150913-1717"

### ISSUE THREAD

**Issue by tao-ji** [SpoonLabs/astor#45]
When using spoon(5.1.0), I am not able to build it because the "org.eclipse.jdt.core:3.12.0.v20150913-1717" has been removed, which has been reported(https://github.com/INRIA/spoon/issues/688).

After changing the version of spoon to 5.2.0-snapshot, I can build it.

**Comment by martinezmatias** [comment]
Thank Tao. It seem that Spoon issue #688 was resolved.
I will upgrade Spoon dependency from Astor's pom when Spoon 5.2.0 is released.
If you have any other question or problem, do not hesitate to write us.
Thanks
Best regards
Matias

**Comment by tao-ji** [comment]
Hi Matias,
After changing the spoon to the latest snapshot version, Astor cannot pass some tests. When running EvoSuiteGenerationTest, it seems that the latest spoon fails to work correctly with Astor. 

The console shows some error information as follows:
[ERROR] fr.inria.astor.util.EvoSuiteFacade.reificateEvoSuiteTest(EvoSuiteFacade.java:162) - Element: double 
Signature: double 
Class: class spoon.support.reflect.reference.CtTypeReferenceImpl 
is set as child of 
Element: functionValueAccuracy 
Signature: double org.apache.commons.math.analysis.solvers.UnivariateRealSolverImpl#functionValueAccuracy 
Class: class spoon.support.reflect.reference.CtFieldReferenceImpl 
however it is visited as a child of 
Element: protected double functionValueAccuracy; 
Signature: double  functionValueAccuracydouble  
Class: class spoon.support.reflect.declaration.CtFieldImpl

To build and run Astor successfully, I decide to use Spoon 5.1.0. I have tried to download the "org.eclipse.jdt.core:3.12.0.v20150913-1717.jar" into my own local repository, but I failed to find this particular version. Would you please send me a copy of "org.eclipse.jdt.core:3.12.0.v20150913-1717.jar"? My email address is "taoji@nudt.edu.cn".
Thanks
Best regards
Tao Ji

**Comment by martinezmatias** [comment]
Hi Tao
I recommend you to ignore that test (EvoSuiteGenerationTest) until the fix is released. 
Astor repair core will continue working without the integration to evosuite.
I will continue working on that.
Best regards
Matias
