### ISSUE TITLE
Arguments used to the experiment

### ISSUE THREAD

**Issue by SoichiSumi** [SpoonLabs/astor#47]
I read astor's paper and the readme, and  succeeded to repair some bugs contained at examples folder.However I couldn't generate patches reported in docs/bugs_repaired.md to some bugs(Math-5,7) downloaded from defects4j manually.
Could you give me more information about how to execute astor on defects4j (or  the bugs not contained in the examples folder of astor)?

For example, I executed astor to math-5 in the following arguments:
\-------
-location ../defects4j/tmp/math-5-buggy
-mode jgenprog -scope local -srcjavafolder /src/java -srctestfolder /src/test/
-binjavafolder /target/classes -bintestfolder /target/test-classes -flthreshold 0.5 -seed 10 -maxtime 100 -stopfirst true  

-failing org.apache.commons.math3.complex.ComplexTest:org.apache.commons.math3.util.FastMathTest
\## obteined by mvn test

-dependencies ./examples/libs/junit-4.10.jar:./examples/libs/hamcrest-core-1.1.jar
\## obteined by mvn dependency:build-classpath

-javacompliancelevel 8 \##how should we determine this argument?
\------

**Comment by martinezmatias** [comment]
Hi Soichi

> -javacompliancelevel  8 ##how should we determine this argument?

This information can be obtained from Defects4J using the 'info' argument on command defects4j.
For example:
defects4j info -p Lang -b 1

Best
Matias

**Comment by SoichiSumi** [comment]
Dear Mr. Matias,
Thanks to your advice, I could generate the patch reported in docs/bugs_repaired.md to Math-5.

Recently, I added some extension to your tool in my research. So I want to replicate your experiment and  evaluate the extension. Could you give me the information about the arguments used in the experiment? Particularly, I want to know the setting about scope used for each bug.

Sincerely,
Soichi Sumi

**Comment by martinezmatias** [comment]
Dear Mr Soichi
> I want to know the setting about scope used for each bug.
Yes, of course. Regarding with the scope argument: Astor accepts three values for scope 'Local', 'Package' and 'Global'. They define the places from where ingredients for the candidate patches are taken. In the ISSTA'16 paper we presented this optimization (the original GenProg does not have this option) and for validation we ran Astor over the Defects4J using those 3 values. 
In you want, we can discuss in private more in details about your experiment and how to customize Astor for carrying out it, you can write me at matias.sebastian.martinez@gmail.com

**Comment by SoichiSumi** [comment]
Dear Mr. Matias,

Thank you for your detailed explanation. I probably understood the arguments used in the experiment!
If I have further question, I'll send you a mail later.

Sincerely,
Soichi Sumi
