### ISSUE TITLE
build failure: Could not resolve dependencies

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/astor#64]
[ERROR] Failed to execute goal on project astor: Could not resolve dependencies for project org.inria.sacha.automaticRepair:astor:jar:0.0.2-SNAPSHOT: Could not find artifact fr.spoonlab:jte:jar:0.0.1 in inria (http://spoon.gforge.inria.fr/repositories/releases/)

**Comment by martinezmatias** [comment]
Solved. New version introduced by commit 55f627381168de35b4164533b473b8d74205942c, which contains several refactors.

**Comment by monperrus** [comment]
Now I have another error:

```
[ERROR] Failed to execute goal on project astor: Could not resolve dependencies for project org.inria.sacha.automaticRepair:astor:jar:0.0.2-SNAPSHOT: Could not find artifact fr.spoonlab:jte:jar:0.0.1 in inria (http://spoon.gforge.inria.fr/repositories/releases/) 
```

**Comment by martinezmatias** [comment]
Sorry, I fault when modifying the pom.xml.  In the previous version I removed section for installing the jar but I forgot to remove the dependency section that referenced to that jar. As in my machine was already in the maven repository It worked, and I assume that in Travis happened the same. Now, fixed. I'll merge after travis validates the branch.

**Comment by monperrus** [comment]
works now! thanks!
