### ISSUE TITLE
when a argument is missing, MainjGenProg does not say which one

### ISSUE THREAD

**Issue by monperrus** [SpoonLabs/astor#71]
Hi Matias,

We're trying to run the Math-issue-280 directly with all arguments (and not with "-bug280").

One argument is missing but we don't know the one.

     fr.inria.main.evolution.MainjGenProg  -srcjavafolder examples/Math-issue-280/src/java/ -srctestfolder examples/Math-issue-280/src/test/  -binjavafolder examples/Math-issue-280/target/classes/ -bintestfolder  examples/Math-issue-280/target/test-classes/

What's the missing argument?

**Comment by martinezmatias** [comment]
Hi Martin
I am pretty sure that the missing argument is "-location".
This argument contains the *absolute* path to the folder where the code under repair is located.
Example, -location  /home/..../astor/examples/math_85 
Then, the the other arguments you included in the command are *relative* path.
For example, argument "-srcjavafolder" has the relative path to the folder that contains the sources of the application. 
Example,  -srcjavafolder /src/java/

The arguments -srcjavafolder, "-srctestfolder", "-binjavafolder" and "-bintestfolder", are optionals (i.e., astor tries to deduce them), but I would say to explicitly include them.
