### ISSUE TITLE
A problem when using ASTOR to repair Chart_3

### ISSUE THREAD

**Issue by DehengYang** [SpoonLabs/astor#75]
I am trying to use ASTOR to repair some bugs. Up to now I have no problem in using ASTOR to repair Math_[id] programs from Defects4j Dataset by following the given ReadMe.md, but fail to repair Chart_3. The command that I write is as follow: 

```
bug=chart_3
mvn dependency:build-classpath | egrep -v "(^\[INFO\]|^\[WARNING\])" | tee /tmp/astor-classpath.txt
cat /tmp/astor-classpath.txt

java -cp $(cat /tmp/astor-classpath.txt):target/classes fr.inria.main.evolution.AstorMain -mode jGenProg -srcjavafolder examples/$bug/source/ -srctestfolder examples/$bug/tests/  -binjavafolder examples/$bug/build/ -bintestfolder  examples/$bug/build-tests/ -location /home/deheng/Astor/astor-master/examples/$bug/ -dependencies examples/$bug/lib/servlet.jar -out ./dale/$bug
```

The output information of the failed repair is : 

```
[ERROR] fr.inria.astor.core.loop.AstorCoreEngine.initModel(AstorCoreEngine.java:1100) - Problem compiling the model with compliance level 8
[ERROR] fr.inria.astor.core.loop.AstorCoreEngine.initModel(AstorCoreEngine.java:1102) - java.io.FileNotFoundException: /home/deheng/Astor/astor-master/./dale/chart3/AstorMain-Chart_3/src/default does not exist

Exception in thread "main" spoon.SpoonException: java.io.FileNotFoundException: /home/deheng/Astor/astor-master/./dale/chart3/AstorMain-Chart_3/src/default does not exist
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.addInputSource(JDTBasedSpoonCompiler.java:213)
	at fr.inria.astor.core.manipulation.MutationSupporter.buildModel(MutationSupporter.java:86)
	at fr.inria.astor.core.loop.AstorCoreEngine.initModel(AstorCoreEngine.java:1097)
	at fr.inria.astor.core.loop.AstorCoreEngine.initPopulation(AstorCoreEngine.java:1031)
	at fr.inria.astor.approaches.ingredientbased.IngredientBasedRepairApproachImpl.initPopulation(IngredientBasedRepairApproachImpl.java:53)
	at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:124)
	at fr.inria.main.evolution.AstorMain.run(AstorMain.java:174)
	at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
	at fr.inria.main.evolution.AstorMain.main(AstorMain.java:207)
Caused by: java.io.FileNotFoundException: /home/deheng/Astor/astor-master/./dale/chart3/AstorMain-Chart_3/src/default does not exist
	at spoon.compiler.SpoonResourceHelper.createFolder(SpoonResourceHelper.java:91)
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.addInputSource(JDTBasedSpoonCompiler.java:210)
	... 8 more

```

I am trying to find the reason by reading the source code but failed. It would be much appreciated if any guidance is given.

**Comment by martinezmatias** [comment]
HI @DehengYang 

I created a test cases for Char_1, which configuration would be similar.

https://github.com/SpoonLabs/astor/commit/0f2d392834ca5e407f4ea283d3906d92341834ce

The command used in that test is: 
[-dependencies <my_path>/astor/./examples/chart_1/lib/iText-2.1.4.jar:<my_path>/astor/./examples/chart_1/lib/servlet.jar:<my_path>/astor/./examples/chart_1/lib/junit.jar: -mode statement -location <my_path>/astor/./examples/chart_1 -srcjavafolder /source/ -srctestfolder /tests/ -binjavafolder /build/ -bintestfolder /build-tests/ -javacompliancelevel 4 -flthreshold 0.1 -out <my_path>/astor/./output_astor -seed 1 -maxgen 100 -stopfirst false -maxtime 10 -package org.jfree -scope fr.inria.astor.core.loop.spaces.ingredients.scopes.ctscopes.CtPackageIngredientScope -loglevel INFO]

Does it work for you?

**Comment by DehengYang** [comment]
Thank you for your reply! I use this command to repair chart_3 with Astor successfully, and in the process I have some questions :
1) Must I write the parameters of `-seed` and `-scope ` in the command for running Astor? I find that Astor fails to repair chart 3 without giving any plausible solution once I remove the `-seed` or `-scope ` parameter. And is there any requirement when setting the value of `seed` or `-scope ` ?
2) Do I need to add the `-failing` parameter into the command? Personally I think there is no need telling Astor the failing tests as it will run 'gzoltar' in the repair process.

Thank you again for your help!

**Comment by martinezmatias** [comment]
Hi @DehengYang 

> Must I write the parameters of -seed and -scope in the command for running Astor?

-scope is not mandatory. It will use the default value.
-seed I would say to use a values e.g., 0, for re-executing the experiment several times and to have always the same results. 

> Do I need to add the -failing parameter into the command? Personally I think there is no need to tell Astor the failing tests as it will run 'gzoltar' in the repair process.

Exact. If it's not specified, Astor obtains the info from the Gzoltar's output.

if you have any question, do not hesitate to write me.
Best regards
Matias

**Comment by DehengYang** [comment]
Thank you for being so patient! It really helps.
