### ISSUE TITLE
Error executing Astor with jGenprog mode

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#84]
Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException

**Comment by martinezmatias** [comment]
Hi @ssk1216 
Do you have the command line or test case you execute that produces that exception?
Thanks
Matias

**Comment by ssk1216** [comment]
java -cp "C:\Users\Achu\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Achu\.m2\repository\fr\inria\gforge\spoon\spoon-core\6.0.0\spoon-core-6.0.0.jar;C:\Users\Achu\.m2\repository\org\eclipse\tycho\org.eclipse.jdt.core\3.13.50.v20171007-0855\org.eclipse.jdt.core-3.13.50.v20171007-0855.jar;C:\Users\Achu\.m2\repository\com\martiansoftware\jsap\2.1\jsap-2.1.jar;C:\Users\Achu\.m2\repository\org\apache\maven\maven-model\3.5.0\maven-model-3.5.0.jar;C:\Users\Achu\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.24\plexus-utils-3.0.24.jar;C:\Users\Achu\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Achu\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Achu\.m2\repository\com\gzoltar\gzoltar\0.1.1\gzoltar-0.1.1.jar;C:\Users\Achu\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\Achu\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Achu\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;C:\Users\Achu\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Achu\.m2\repository\fil\iagl\cocospoon\CocoSpoon\1.0.0-SNAPSHOT\CocoSpoon-1.0.0-SNAPSHOT.jar;C:\Users\Achu\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-assert\1.4\fest-assert-1.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-util\1.1.6\fest-util-1.1.6.jar;C:\Users\Achu\.m2\repository\com\sanityinc\jargs\2.0-SNAPSHOT\jargs-2.0-SNAPSHOT.jar;target\classes" fr.inria.main.evolution.AstorMain  -mode jgenProg  -srcjavafolder examples\Math-issue-280\src\java\ -srctestfolder examples\Math-issue-280\src\test\  -binjavafolder examples\Math-issue-280\target\classes\   -bintestfolder  examples\Math-issue-280\target\test-classes\ -location \astor\examples\Math-issue-280\ -dependencies examples\Math-issue-280\lib

**Comment by ssk1216** [comment]
& the output is this:

2018-05-02 14:37:26,593 INFO main - command line arguments: [-mode  jgenProg  -srcjavafolder  examples\Math-issue-280\src\java\  -srctestfolder  examples\Math-issue-280\src\test\  -binjavafolder  examples\Math-issue-280\target\classes\  -bintestfolder  examples\Math-issue-280\target\test-classes\  -location  \astor\examples\Math-issue-280\  -dependencies  examples\Math-issue-280\lib]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:810) - Source folders: []
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:829) - Source Test folders: []
[INFO ] fr.inria.astor.core.setup.ProjectConfiguration.addLocationToClasspath(ProjectConfiguration.java:140) - Adding to classpath junit-4.4.jar
[ERROR] fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:48) - Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:49)
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:22)
        at fr.inria.main.evolution.PlugInVisitor.loadCompiler(PlugInVisitor.java:191)
        at fr.inria.main.evolution.PlugInVisitor.load(PlugInVisitor.java:272)
        at fr.inria.astor.core.ingredientbased.IngredientBasedPlugInLoader.load(IngredientBasedPlugInLoader.java:133)
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1013)
        at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:107)
        at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
        at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
        at fr.inria.main.evolution.AstorMain.main(AstorMain.java:207)

**Comment by ssk1216** [comment]
But I followed the documentation on the https://github.com/SpoonLabs/astor/blob/master/docs/getting-starting.md

**Comment by ssk1216** [comment]
with the new updated command line, 
java -cp "C:\Users\Achu\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Achu\.m2\repository\fr\inria\gforge\spoon\spoon-core\6.0.0\spoon-core-6.0.0.jar;C:\Users\Achu\.m2\repository\org\eclipse\tycho\org.eclipse.jdt.core\3.13.50.v20171007-0855\org.eclipse.jdt.core-3.13.50.v20171007-0855.jar;C:\Users\Achu\.m2\repository\com\martiansoftware\jsap\2.1\jsap-2.1.jar;C:\Users\Achu\.m2\repository\org\apache\maven\maven-model\3.5.0\maven-model-3.5.0.jar;C:\Users\Achu\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.24\plexus-utils-3.0.24.jar;C:\Users\Achu\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Achu\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Achu\.m2\repository\com\gzoltar\gzoltar\0.1.1\gzoltar-0.1.1.jar;C:\Users\Achu\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\Achu\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Achu\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;C:\Users\Achu\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Achu\.m2\repository\fil\iagl\cocospoon\CocoSpoon\1.0.0-SNAPSHOT\CocoSpoon-1.0.0-SNAPSHOT.jar;C:\Users\Achu\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-assert\1.4\fest-assert-1.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-util\1.1.6\fest-util-1.1.6.jar;C:\Users\Achu\.m2\repository\com\sanityinc\jargs\2.0-SNAPSHOT\jargs-2.0-SNAPSHOT.jar;target\classes" fr.inria.main.evolution.AstorMain  -mode jgenProg  -srcjavafolder src\java\ -srctestfolder src\test\  -binjavafolder target\classes\   -bintestfolder  target\test-classes\ -location D\astor\examples\Math-issue-280\ -dependencies D\astor\examples\Math-issue-280\lib

_

1. I found there was no test-classes folder in the target folder. 
2. the mvn clean compile test command result was BUILD FAILURE    ANY SUGGESTIONS????

Thanks Martin, your inputs have helped me to proceed with the tool, bcoz the intial documentation(the link i posted) was a bit confusing.

**Comment by martinezmatias** [comment]
Hi @ssk1216 

> your inputs have helped me to proceed with the tool, bcoz the intial documentation(the link i posted) was a bit confusing.

Okey, I will improve it.

> the  mvn clean compile test command result was BUILD FAILURE ANY SUGGESTIONS????
Do you mean the compilation of the example (<path>\astor\examples\Math-issue-280\)?

> I found there was no test-classes folder in the target folder

Chech if the target folder of the example you want to try has the classes. If not, run maven on the root folder of the example

**Comment by ssk1216** [comment]
Any help on this please?

**Comment by ssk1216** [comment]
try {
			Class classDefinition = Class.forName(className);
			object = classDefinition.newInstance();
		} catch (Exception e) {
			log.error("Loading " + className + " --" + e);
			throw new Exception("Error Loading Engine: " + e);

**Comment by martinezmatias** [comment]
Hi @ssk1216 
Could you send me the command line to reproduce the error?
Best regards
Matias

**Comment by ssk1216** [comment]
D:\astor>java -cp "C:\Users\Achu\.m2\repository\log4j\log4j\1.2.17\log4j-1.2.17.jar;C:\Users\Achu\.m2\repository\fr\inria\gforge\spoon\spoon-core\6.0.0\spoon-core-6.0.0.jar;C:\Users\Achu\.m2\repository\org\eclipse\tycho\org.eclipse.jdt.core\3.13.50.v20171007-0855\org.eclipse.jdt.core-3.13.50.v20171007-0855.jar;C:\Users\Achu\.m2\repository\com\martiansoftware\jsap\2.1\jsap-2.1.jar;C:\Users\Achu\.m2\repository\org\apache\maven\maven-model\3.5.0\maven-model-3.5.0.jar;C:\Users\Achu\.m2\repository\org\codehaus\plexus\plexus-utils\3.0.24\plexus-utils-3.0.24.jar;C:\Users\Achu\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;C:\Users\Achu\.m2\repository\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\Achu\.m2\repository\com\gzoltar\gzoltar\0.1.1\gzoltar-0.1.1.jar;C:\Users\Achu\.m2\repository\junit\junit\4.11\junit-4.11.jar;C:\Users\Achu\.m2\repository\org\hamcrest\hamcrest-core\1.3\hamcrest-core-1.3.jar;C:\Users\Achu\.m2\repository\commons-cli\commons-cli\1.2\commons-cli-1.2.jar;C:\Users\Achu\.m2\repository\com\googlecode\json-simple\json-simple\1.1\json-simple-1.1.jar;C:\Users\Achu\.m2\repository\fil\iagl\cocospoon\CocoSpoon\1.0.0-SNAPSHOT\CocoSpoon-1.0.0-SNAPSHOT.jar;C:\Users\Achu\.m2\repository\org\apache\commons\commons-lang3\3.4\commons-lang3-3.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-assert\1.4\fest-assert-1.4.jar;C:\Users\Achu\.m2\repository\org\easytesting\fest-util\1.1.6\fest-util-1.1.6.jar;C:\Users\Achu\.m2\repository\com\sanityinc\jargs\2.0-SNAPSHOT\jargs-2.0-SNAPSHOT.jar;target\classes" fr.inria.main.evolution.AstorMain  -mode jgenProg  -srcjavafolder src\java\ -srctestfolder src\test\  -binjavafolder target\classes\   -bintestfolder  target\test-classes\ -location D:\astor\examples\Math-issue-280\ -dependencies \ examples\Math-issue-280\lib
2018-05-07 11:10:32,484 INFO main - command line arguments: [-mode  jgenProg  -srcjavafolder  src\java\  -srctestfolder  src\test\  -binjavafolder  target\classes\  -bintestfolder  target\test-classes\  -location  D:\astor\examples\Math-issue-280\  -dependencies  \  examples\Math-issue-280\lib]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:814) - Source folders: [D:\astor\examples\Math-issue-280\src\java]
[INFO ] fr.inria.main.AbstractMain.determineSourceFolders(AbstractMain.java:833) - Source Test folders: [D:\astor\examples\Math-issue-280\src\test]
originalBin=target\classes\
D:\astor\examples\Math-issue-280\target\test-classes
ce=fr.inria.astor.core.setup.ProjectRepairFacade@1f021e6c
dfdfdffr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler
[ERROR] fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:49) - Loading fr.inria.astor.core.manipulation.bytecode.compiler.SpoonClassCompiler --java.lang.NullPointerException
Exception in thread "main" java.lang.Exception: Error Loading Engine: java.lang.NullPointerException
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:50)
        at fr.inria.main.evolution.PlugInLoader.loadPlugin(PlugInLoader.java:22)
        at fr.inria.main.evolution.PlugInVisitor.loadCompiler(PlugInVisitor.java:191)
        at fr.inria.main.evolution.PlugInVisitor.load(PlugInVisitor.java:272)
        at fr.inria.astor.core.ingredientbased.IngredientBasedPlugInLoader.load(IngredientBasedPlugInLoader.java:133)
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.loadExtensionPoints(AstorCoreEngine.java:1013)
        at fr.inria.main.evolution.AstorMain.createEngine(AstorMain.java:107)
        at fr.inria.main.evolution.AstorMain.run(AstorMain.java:176)
        at fr.inria.main.evolution.AstorMain.execute(AstorMain.java:230)
        at fr.inria.main.evolution.AstorMain.main(AstorMain.java:207)

**Comment by martinezmatias** [comment]
Thanks, does that command correspond to a test case?

**Comment by ssk1216** [comment]
I have used the same command line arguments and the tried to execute jGenprog.

It fails at loading SpoonClassCompiler. Is there any instruction missing on the link w.r.t Spoon

**Comment by martinezmatias** [comment]
Okey, I would say that the best way is to take a test case and examine the arguments.
For example:
https://github.com/SpoonLabs/astor/blob/master/src/test/java/fr/inria/astor/test/repair/approaches/JGenProgTest.java#L403


From the command you sent me there are some mistakes: e.g., -dependencies \ examples\Math-issue-280\lib:
There, the path must be absolute.

**Comment by ssk1216** [comment]
This looks to me an issue related to Spoon. 

All arguments are OK.  

just tried with the updated commandline full path for dependencies

Still doesn't run .same error
