### ISSUE TITLE
Use proper release numbering

### ISSUE THREAD

**Issue by surli** [SpoonLabs/astor#88]
Astor is always released under version number 0.0.2-SNAPSHOT since a while: as a result, I'm not able anymore to compile repairnator 1.0 because changes have been made on the API since then.

Is it possible to start doing some real releases and upgrading version number? It's pretty easy to get rights for releasing on oss.

**Comment by monperrus** [comment]
works well, see https://github.com/tdurieux/maven-repository/tree/master/releases/org/inria/sacha/automaticRepair/astor
