### ISSUE TITLE
- The Process that runs JUnit test cases had problems: Cannot run program "/bin/bash" (in directory "D:\astor\examples\Math-issue-280"): CreateProcess error=2, The system cannot find the file specified Exception in thread "main" java.lang.IllegalStateException: Initial run of test suite fails

### ISSUE THREAD

**Issue by ssk1216** [SpoonLabs/astor#96]
LaucherJUnitProcess has a code 
ProcessBuilder pb = new ProcessBuilder("/bin/bash"); 

As I am executing on windows, I get the below error,

[INFO ] fr.inria.astor.core.solutionsearch.population.ProgramVariantFactory.createProgramInstance(ProgramVariantFactory.java:127) - Total suspicious from FL: 72,  64
[INFO ] fr.inria.astor.core.solutionsearch.population.ProgramVariantFactory.createProgramInstance(ProgramVariantFactory.java:136) - Total ModPoint created: 64
[INFO ] fr.inria.astor.core.solutionsearch.population.ProgramVariantFactory.createInitialPopulation(ProgramVariantFactory.java:82) - Creating program variant #1, [Variant id: 1, #gens: 64, #ops: 0, parent:-]
[INFO ] fr.inria.astor.core.validation.processbased.LaucherJUnitProcess.execute(LaucherJUnitProcess.java:138) - The Process that runs JUnit test cases had problems: Cannot run program "/bin/bash" (in directory "D:\astor\examples\Math-issue-280"): CreateProcess error=2, The system cannot find the file specified
Exception in thread "main" java.lang.IllegalStateException: Initial run of test suite fails
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.setFitnessOfPopulation(AstorCoreEngine.java:1102)
        at fr.inria.astor.core.solutionsearch.AstorCoreEngine.initPopulation(AstorCoreEngine.java:1085)

Any suggestions on this please

**Comment by monperrus** [comment]
I would suggest to run Astor in a Linux machine on top of VirtualBox.

**Comment by martinezmatias** [comment]
I seems the problems in on Windows platform.  
We can create a VirtualBox with a Windows.
(We are almost sure that on linux works due Travis uses it on its dockers:  OS/Arch:      linux/amd64)

**Comment by ssk1216** [comment]
Astor works fine on Linux :)
